name: Cabin Africa CI CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build & Deploy
        env:
            ID_RSA: ${{ secrets.SSH_ID_RSA }}
            HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
            USER_NAME: ${{ secrets.SSH_USER_NAME }}
     
        run: |
          # Create private key file
          echo "$ID_RSA" > id_rsa
          chmod 600 id_rsa # Set the correct permissions

          # Start the SSH agent
          eval "$(ssh-agent -s)"
          ssh-add id_rsa # Add the private key to the agent

          # Run your deployment commands
          ssh -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME << 'EOF'
            # Place your deployment commands here
            echo "Deploying application..."
            # Example: git pull, npm install, etc.
          EOF
