name: Cabin Africa CI CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
            USER_NAME: ${{ secrets.SSH_USER_NAME }}
     
        run: |
          # Create private key file
          echo "$PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa # Set the correct permissions

          # Start the SSH agent
          eval "$(ssh-agent -s)"
          ssh-add id_rsa # Add the private key to the agent

          # Run your deployment commands
          ssh -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME << 'EOF'
            set -e # Exit immediately if a command exits with a non-zero status
            
            # Navigate to application directory
            cd /home/ubuntu/next-ec2-demo || exit

            # Update package list and pull latest changes
            sudo yum update -y
            sudo git pull origin main
             
            # Build the application
            sudo npm run build

            # Restart the application using PM2
            sudo pm2 restart cabin-frontend
          EOF
